"""
Environment — receives tool calls and returns simulated responses.

Tool responses are generated by the LLM using the scenario context so they
are internally consistent with the task details (order IDs, product names,
dates, amounts, etc.).  Results are cached per-signature to guarantee
consistency when the same tool call is repeated.
"""

import copy
import json
from typing import Any, Dict, List, Optional

from .conversation_state import ToolCallRecord, ToolResultRecord
from .llm_provider import LLMProvider
from .toolset import PROCESS_RETURN_RESULTS


# ---------------------------------------------------------------------------
# System prompt for the tool-response simulator
# ---------------------------------------------------------------------------

_TOOL_SIM_SYSTEM_PROMPT = """\
You are a backend system simulator for a customer support platform.

Given scenario context and a tool call, generate a plausible JSON response
that is consistent with the scenario details (order IDs, product names, dates,
amounts, etc.).

Rules:
- Return ONLY a valid JSON object (no markdown fences, no explanation).
- If a "Canonical Order Record" is provided, use its values EXACTLY (same order_id,
  item names, prices, delivery dates, customer_id, payment method, address).
  Do NOT modify, invent, or deviate from any value present in the canonical record.
- For agent-side tools (any tool NOT prefixed with "customer_"): return only
  CRM-visible facts (order_id, items, prices, delivery status/dates, payment,
  promotions, shipping address). Do NOT include item condition, inspection findings,
  usage history, or any information about how the customer used or handled an item —
  those facts are disclosed through conversation, not stored in CRM.
- For customer-facing tools (prefixed with "customer_"): return all order details
  including delivery status. Still do not invent facts not in the scenario context.
- For write tools: return a success confirmation with relevant IDs and status.
- Use details from the scenario context wherever possible.
- Do NOT contradict the scenario facts.
- For customer_id fields, always use a system-generated ID format (e.g., CUST-XXXXXXXX).
  Do NOT use the customer's name, Persona_id, or any other non-numeric identifier.
"""


# ---------------------------------------------------------------------------
# System prompt for the return-fact verifier
# ---------------------------------------------------------------------------

_RETURN_VERIFICATION_SYSTEM_PROMPT = """\
You are a fact-verification module for a customer support system.

You will be given:
1. The GROUND TRUTH scenario — what actually happened with this order.
2. The CUSTOMER STATEMENTS — what the customer claimed during the conversation.
3. The PROCESS RETURN ARGUMENTS — what the agent is about to submit.

Your task: identify facts in the customer statements that CONTRADICT or SIGNIFICANTLY DIFFER
from the ground truth. Focus only on:
- Item conditions (opened, used, damaged, defective)
- Return reason (why the customer says they are returning)
- Which items are being returned
- Delivery timing (if relevant to return eligibility)

Do NOT flag:
- Facts that are absent from customer statements (missing detail is not a lie)
- Minor phrasing differences or synonym variation
- Policy interpretations (your job is fact-checking only)
- Anything confirmed by tool results in the conversation

Return ONLY valid JSON:
{
  "verified": true or false,
  "discrepancies": [
    {
      "field": "string (e.g. item_condition, return_reason, items_in_return)",
      "customer_claim": "string — what the customer said",
      "actual": "string — what the ground truth says",
      "severity": "minor or major"
    }
  ],
  "verification_hints": [
    "string — a neutral clarifying question the agent can ask the customer to surface the correct fact"
  ]
}

Set verified=true if there are no MAJOR discrepancies. Minor discrepancies alone do not block verification.
"""


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

class Environment:
    """Simulates tool execution by generating plausible responses."""

    def __init__(
        self,
        scenario: Dict[str, Any],
        llm_provider: LLMProvider,
        sim_model: Optional[str] = None,
        sim_temperature: float = 0.3,
        sim_max_tokens: int = 1000,
    ):
        self.scenario = scenario
        self.llm_provider = llm_provider
        self.sim_model = sim_model
        self.sim_temperature = sim_temperature
        self.sim_max_tokens = sim_max_tokens

        # Cache: signature -> result dict
        self._cache: Dict[str, Dict[str, Any]] = {}

        # Canonical order record: populated from the first order lookup result.
        # All subsequent order lookups use it as authoritative context so that
        # order_id, item names, prices, dates, addresses are consistent across
        # customer and agent tool calls.
        self._canonical_order_record: Optional[Dict[str, Any]] = None

        # Pre-extract scenario contexts once (agent tools see order-facts only;
        # customer tools see the full order minus policy-analysis metadata)
        self._agent_tool_context = self._build_agent_tool_context()
        self._customer_tool_context = self._build_customer_tool_context()

    # ----- public API -----

    def execute_tool(self, tool_call: ToolCallRecord) -> ToolResultRecord:
        """Execute a tool call, returning a simulated result.

        Results are cached by ``(tool_name, arguments)`` signature so that
        repeated identical calls produce identical responses.
        """
        sig = self._signature(tool_call)

        if sig in self._cache:
            return ToolResultRecord(
                tool_call_id=tool_call.tool_call_id,
                tool_name=tool_call.tool_name,
                result=self._cache[sig],
            )

        # Special-case: deterministic handlers
        if tool_call.tool_name == "get_policy_info":
            result = self._handle_get_policy_info(tool_call.arguments)
        elif tool_call.tool_name == "process_return":
            result = self._handle_process_return(tool_call.arguments)
        else:
            result = self._generate_tool_response(tool_call)

        self._cache[sig] = result
        return ToolResultRecord(
            tool_call_id=tool_call.tool_call_id,
            tool_name=tool_call.tool_name,
            result=result,
        )

    # ----- deterministic handlers -----

    def _handle_get_policy_info(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return relevant policy excerpts directly from the scenario."""
        policy = self.scenario.get("Policy", {})
        primary = policy.get("Primary Policy", {})
        related = policy.get("Related policies", [])

        policy_type = arguments.get("policy_type", "all")
        query = arguments.get("query", "")

        # Collect all policy text
        texts = []
        if primary.get("text"):
            texts.append({"source": "primary_policy", "text": primary["text"]})
        for i, rp in enumerate(related or []):
            if rp.get("text"):
                texts.append({
                    "source": f"related_policy_{i + 1}",
                    "url": rp.get("url", ""),
                    "text": rp["text"],
                })

        return {
            "status": "success",
            "policy_type": policy_type,
            "query": query,
            "policies": texts,
        }

    def _handle_process_return(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return deterministic result based on resolution_type."""
        resolution_type = arguments.get("resolution_type", "")
        order_id = arguments.get("order_id", "UNKNOWN")

        if resolution_type not in PROCESS_RETURN_RESULTS:
            return {
                "status": "error",
                "resolution_type": resolution_type,
                "message": f"Unknown resolution_type: {resolution_type}",
            }

        result = copy.deepcopy(PROCESS_RETURN_RESULTS[resolution_type])
        # Substitute order_id placeholders
        for key, value in result.items():
            if isinstance(value, str) and "{order_id}" in value:
                result[key] = value.replace("{order_id}", order_id)

        result["order_id"] = order_id
        result["customer_id"] = arguments.get("customer_id", "UNKNOWN")
        return result

    # ----- LLM-based response generation -----

    _ORDER_LOOKUP_TOOLS = frozenset({"get_order_details", "customer_view_order_details"})

    def _generate_tool_response(self, tool_call: ToolCallRecord) -> Dict[str, Any]:
        """Use the LLM to produce a plausible tool response."""
        user_prompt = self._build_tool_sim_prompt(tool_call)

        messages = [
            {"role": "system", "content": _TOOL_SIM_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = self.llm_provider.call_text_only(
                messages=messages,
                temperature=self.sim_temperature,
                max_tokens=self.sim_max_tokens,
            )
            result = self._parse_sim_response(response.content or "{}")
        except Exception as e:
            result = {
                "status": "success",
                "tool_name": tool_call.tool_name,
                "note": f"Simulated response (generation failed: {e})",
            }

        # Store the first order lookup as the canonical record so all subsequent
        # order queries (regardless of tool name) reference the same facts.
        if (
            self._canonical_order_record is None
            and tool_call.tool_name in self._ORDER_LOOKUP_TOOLS
            and result.get("order_id")
        ):
            self._canonical_order_record = result

        return result

    def _build_tool_sim_prompt(self, tool_call: ToolCallRecord) -> str:
        """Construct the user prompt for the tool-response simulator.

        Customer tools receive the full order context (minus policy-analysis metadata).
        Agent tools receive only CRM-style order facts — no return narrative or conditions.
        When a canonical order record exists, it is injected as the authoritative
        reference to guarantee consistency across all tool calls.
        """
        is_customer_tool = tool_call.tool_name.startswith("customer_")
        context = (
            self._customer_tool_context if is_customer_tool else self._agent_tool_context
        )
        parts = [
            "## Scenario Context",
            context,
            "",
        ]

        if (
            self._canonical_order_record is not None
            and tool_call.tool_name in self._ORDER_LOOKUP_TOOLS
        ):
            parts += [
                "## Canonical Order Record (authoritative — match these values exactly)",
                json.dumps(self._canonical_order_record, ensure_ascii=False),
                "",
            ]
            if not is_customer_tool:
                parts += [
                    "IMPORTANT: For this agent-side tool response, omit all item condition,",
                    "inspection, or usage information even if present in the canonical record.",
                    "",
                ]

        parts += [
            "## Tool Call",
            f"Tool: {tool_call.tool_name}",
            f"Arguments: {json.dumps(tool_call.arguments, ensure_ascii=False)}",
            "",
            "Generate a realistic JSON response for this tool call.",
        ]
        return "\n".join(parts)

    # ----- verification -----

    def verify_return(
        self, history: List[Dict[str, Any]], arguments: Dict[str, Any]
    ) -> Dict[str, Any]:
        """LLM-based fact check: customer claims vs scenario ground truth.

        Returns {"verified": bool, "discrepancies": [...], "verification_hints": [...]}.
        Fails open (verified=True) on any exception so the conversation is never blocked
        by a verification infrastructure failure.
        """
        task = self.scenario.get("task", {})
        ground_truth = task.get("detail") or task.get("task") or "(not available)"

        customer_msgs = [
            t.get("message", "")
            for t in history
            if t.get("turn") == "customer" and t.get("message")
        ]
        customer_text = "\n".join(f"- {m}" for m in customer_msgs) or "(none)"

        user_prompt = "\n".join([
            "## Ground Truth Scenario",
            ground_truth,
            "",
            "## Customer Statements (from conversation)",
            customer_text,
            "",
            "## Process Return Arguments",
            json.dumps(arguments, ensure_ascii=False),
            "",
            "Verify the customer statements against the ground truth.",
        ])

        messages = [
            {"role": "system", "content": _RETURN_VERIFICATION_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]
        try:
            response = self.llm_provider.call_text_only(
                messages=messages,
                temperature=0.0,
                max_tokens=800,
            )
            result = self._parse_sim_response(response.content or "{}")
            if "verified" not in result:
                return {"verified": True, "discrepancies": [], "verification_hints": []}
            return result
        except Exception as e:
            print(f"  [Environment] verify_return failed ({e}); proceeding as verified.")
            return {"verified": True, "discrepancies": [], "verification_hints": []}

    # ----- helpers -----

    # Policy-analysis fields the customer would never see in their own order view
    _CUSTOMER_EXCLUDED_KEYS = frozenset({
        "related_policy_issues", "all_ambiguity_types",
        "primary_ambiguity_type", "stratum_label",
        "complexity_level", "complexity_ordinal",
    })

    # CRM order-record fields visible to an agent tool call
    _ORDER_FACT_KEYS = frozenset({
        "order_id", "order_number", "order_date", "delivery_date",
        "products_involved", "quantities", "prices", "payment_method",
    })

    def _build_agent_tool_context(self) -> str:
        """CRM-style order facts only — no narrative, conditions, or return context.

        Deliberately excludes first_customer_message so the simulator cannot infer
        item conditions from what the customer said; those must come through conversation.
        Uses structured fields when present, falls back to task detail prose.
        """
        task = self.scenario.get("task", {})
        order_facts = {k: task[k] for k in self._ORDER_FACT_KEYS if k in task}
        parts = []
        if order_facts:
            parts.append(f"Order facts: {json.dumps(order_facts, ensure_ascii=False)}")
        elif task.get("detail"):
            parts.append(f"Order facts: {task['detail']}")
        persona = self.scenario.get("persona", {})
        if persona:
            parts.append(f"Customer profile: {json.dumps(persona, ensure_ascii=False)}")
        sid = self.scenario.get("scenario_id", "")
        if sid:
            parts.append(f"Scenario ID: {sid}")
        return "\n".join(parts) if parts else "(no scenario context available)"

    def _build_customer_tool_context(self) -> str:
        """Full order and return details minus internal policy-analysis metadata."""
        task = self.scenario.get("task", {})
        customer_task = {
            k: v for k, v in task.items()
            if k not in self._CUSTOMER_EXCLUDED_KEYS
        }
        parts = [f"Order and return details: {json.dumps(customer_task, ensure_ascii=False)}"]
        name = self.scenario.get("persona", {}).get("Name", "Customer")
        parts.append(f"Customer name: {name}")
        sid = self.scenario.get("scenario_id", "")
        if sid:
            parts.append(f"Scenario ID: {sid}")
        return "\n".join(parts)

    @staticmethod
    def _signature(tool_call: ToolCallRecord) -> str:
        args_norm = json.dumps(tool_call.arguments, sort_keys=True, ensure_ascii=False)
        return f"{tool_call.tool_name}::{args_norm}"

    @staticmethod
    def _parse_sim_response(text: str) -> Dict[str, Any]:
        """Parse JSON from the simulator LLM output."""
        t = text.strip()
        # Strip markdown fences
        if t.startswith("```"):
            lines = t.split("\n")
            t = "\n".join(lines[1:])
            if t.endswith("```"):
                t = t[:-3].strip()

        try:
            parsed = json.loads(t)
            if isinstance(parsed, dict):
                return parsed
            return {"data": parsed}
        except json.JSONDecodeError:
            # Try to extract an object
            start = t.find("{")
            end = t.rfind("}")
            if start != -1 and end != -1 and end > start:
                try:
                    return json.loads(t[start : end + 1])
                except json.JSONDecodeError:
                    pass
            return {"status": "success", "raw_response": t[:500]}
