"""
Environment — receives tool calls and returns simulated responses.

Tool responses are generated by the LLM using the scenario context so they
are internally consistent with the task details (order IDs, product names,
dates, amounts, etc.).  Results are cached per-signature to guarantee
consistency when the same tool call is repeated.
"""

import copy
import json
from typing import Any, Dict, Optional

from conversation_state import ToolCallRecord, ToolResultRecord
from llm_provider import LLMProvider

# Import deterministic return results
import sys
from pathlib import Path

_THIS_DIR = str(Path(__file__).resolve().parent)
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

from toolset import PROCESS_RETURN_RESULTS  # noqa: E402


# ---------------------------------------------------------------------------
# System prompt for the tool-response simulator
# ---------------------------------------------------------------------------

_TOOL_SIM_SYSTEM_PROMPT = """\
You are a backend system simulator for a customer support platform.

Given scenario context and a tool call, generate a plausible JSON response
that is consistent with the scenario details (order IDs, product names, dates,
amounts, conditions, etc.).

Rules:
- Return ONLY a valid JSON object (no markdown fences, no explanation).
- The response must be realistic and internally consistent with the scenario.
- For read tools: return the information that would exist in the system.
- For write tools: return a success confirmation with relevant IDs and status.
- Use details from the scenario context wherever possible.
- Do NOT contradict the scenario facts.
"""


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

class Environment:
    """Simulates tool execution by generating plausible responses."""

    def __init__(
        self,
        scenario: Dict[str, Any],
        llm_provider: LLMProvider,
        sim_model: Optional[str] = None,
        sim_temperature: float = 0.3,
        sim_max_tokens: int = 1000,
    ):
        self.scenario = scenario
        self.llm_provider = llm_provider
        self.sim_model = sim_model
        self.sim_temperature = sim_temperature
        self.sim_max_tokens = sim_max_tokens

        # Cache: signature -> result dict
        self._cache: Dict[str, Dict[str, Any]] = {}

        # Pre-extract scenario context once
        self._scenario_context = self._build_scenario_context()

    # ----- public API -----

    def execute_tool(self, tool_call: ToolCallRecord) -> ToolResultRecord:
        """Execute a tool call, returning a simulated result.

        Results are cached by ``(tool_name, arguments)`` signature so that
        repeated identical calls produce identical responses.
        """
        sig = self._signature(tool_call)

        if sig in self._cache:
            return ToolResultRecord(
                tool_call_id=tool_call.tool_call_id,
                tool_name=tool_call.tool_name,
                result=self._cache[sig],
            )

        # Special-case: deterministic handlers (avoids extra LLM call per tool)
        if tool_call.tool_name == "get_policy_info":
            result = self._handle_get_policy_info(tool_call.arguments)
        elif tool_call.tool_name == "process_return":
            result = self._handle_process_return(tool_call.arguments)
        elif tool_call.tool_name == "get_order_details":
            result = self._handle_get_order_details(tool_call.arguments)
        elif tool_call.tool_name == "check_return_eligibility":
            result = self._handle_check_return_eligibility(tool_call.arguments)
        elif tool_call.tool_name == "get_product_details":
            result = self._handle_get_product_details(tool_call.arguments)
        elif tool_call.tool_name == "get_customer_purchase_history":
            result = self._handle_get_customer_purchase_history(tool_call.arguments)
        elif tool_call.tool_name == "get_return_status":
            result = self._handle_get_return_status(tool_call.arguments)
        else:
            result = self._generate_tool_response(tool_call)

        self._cache[sig] = result
        return ToolResultRecord(
            tool_call_id=tool_call.tool_call_id,
            tool_name=tool_call.tool_name,
            result=result,
        )

    # ----- deterministic handlers -----

    def _handle_get_policy_info(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return relevant policy excerpts directly from the scenario."""
        policy = self.scenario.get("Policy", {})
        primary = policy.get("Primary Policy", {})
        related = policy.get("Related policies", [])

        policy_type = arguments.get("policy_type", "all")
        query = arguments.get("query", "")

        # Collect all policy text
        texts = []
        if primary.get("text"):
            texts.append({"source": "primary_policy", "text": primary["text"]})
        for i, rp in enumerate(related or []):
            if rp.get("text"):
                texts.append({
                    "source": f"related_policy_{i + 1}",
                    "url": rp.get("url", ""),
                    "text": rp["text"],
                })

        return {
            "status": "success",
            "policy_type": policy_type,
            "query": query,
            "policies": texts,
        }

    def _handle_process_return(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return deterministic result based on resolution_type."""
        resolution_type = arguments.get("resolution_type", "")
        order_id = arguments.get("order_id", "UNKNOWN")

        if resolution_type not in PROCESS_RETURN_RESULTS:
            return {
                "status": "error",
                "resolution_type": resolution_type,
                "message": f"Unknown resolution_type: {resolution_type}",
            }

        result = copy.deepcopy(PROCESS_RETURN_RESULTS[resolution_type])
        # Substitute order_id placeholders
        for key, value in result.items():
            if isinstance(value, str) and "{order_id}" in value:
                result[key] = value.replace("{order_id}", order_id)

        result["order_id"] = order_id
        result["customer_id"] = arguments.get("customer_id", "UNKNOWN")
        return result

    def _handle_get_order_details(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return order details derived from scenario task."""
        task = self.scenario.get("task", {})
        persona = self.scenario.get("persona", {})
        items = task.get("items", [])
        return {
            "status": "success",
            "order_id": task.get("order_id", arguments.get("order_id", "UNKNOWN")),
            "customer_name": persona.get("Name", "Customer"),
            "customer_id": f"CID-{persona.get('Name', 'CUST').replace(' ', '').upper()[:8]}",
            "order_date": task.get("purchase_date", "2025-01-01"),
            "delivery_date": task.get("delivery_date", "2025-01-10"),
            "items": [
                {
                    "product_id": item.get("product_id", f"PROD-{i}"),
                    "product_name": item.get("product_name", "Unknown Product"),
                    "quantity": item.get("quantity", 1),
                    "price": item.get("selling_price", 0),
                    "seller": "Amazon" if item.get("is_amazon_seller") == "Y" else "Third-Party Seller",
                }
                for i, item in enumerate(items)
            ],
            "total_amount": sum(
                float(str(item.get("selling_price", 0)).replace("$", "").replace(",", "") or 0)
                for item in items
            ),
            "shipping_address": persona.get("Location", "Unknown"),
        }

    def _handle_check_return_eligibility(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return eligibility status from scenario context."""
        task = self.scenario.get("task", {})
        items = task.get("items", [])
        reasons = task.get("return_reasons", {})
        reason = list(reasons.values())[0] if reasons else "Customer request"
        return {
            "status": "success",
            "eligible": True,
            "reason": reason,
            "return_window_days": 30,
            "days_since_delivery": task.get("days_since_delivery", 7),
            "items_eligible": [
                {"product_name": item.get("product_name", "Item"), "eligible": True}
                for item in items
            ],
            "policy_note": "Item falls within the standard 30-day return window.",
        }

    def _handle_get_product_details(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return product details from scenario items list."""
        task = self.scenario.get("task", {})
        items = task.get("items", [])
        product_id = arguments.get("product_id", "")
        # Match by product_id or fall back to first item
        item = next(
            (i for i in items if str(i.get("product_id", "")) == str(product_id)),
            items[0] if items else {},
        )
        return {
            "status": "success",
            "product_id": item.get("product_id", product_id or "UNKNOWN"),
            "product_name": item.get("product_name", "Unknown Product"),
            "description": item.get("description", ""),
            "price": item.get("selling_price", 0),
            "category": item.get("category", "General"),
            "seller": "Amazon" if item.get("is_amazon_seller") == "Y" else "Third-Party Seller",
            "return_policy": "30-day return window applies.",
        }

    def _handle_get_customer_purchase_history(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return a minimal synthetic purchase history."""
        persona = self.scenario.get("persona", {})
        task = self.scenario.get("task", {})
        return {
            "status": "success",
            "customer_name": persona.get("Name", "Customer"),
            "total_orders": 5,
            "return_rate": "10%",
            "recent_orders": [
                {
                    "order_id": task.get("order_id", "UNKNOWN"),
                    "status": "delivered",
                    "return_requested": True,
                }
            ],
            "account_standing": "good",
        }

    def _handle_get_return_status(self, arguments: Dict[str, Any]) -> Dict[str, Any]:
        """Return 'no prior return' status (fresh conversation)."""
        task = self.scenario.get("task", {})
        return {
            "status": "success",
            "order_id": arguments.get("order_id", task.get("order_id", "UNKNOWN")),
            "return_status": "not_initiated",
            "message": "No return has been initiated for this order yet.",
        }

    # ----- LLM-based response generation -----

    def _generate_tool_response(self, tool_call: ToolCallRecord) -> Dict[str, Any]:
        """Use the LLM to produce a plausible tool response."""
        user_prompt = self._build_tool_sim_prompt(tool_call)

        messages = [
            {"role": "system", "content": _TOOL_SIM_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = self.llm_provider.call_text_only(
                messages=messages,
                temperature=self.sim_temperature,
                max_tokens=self.sim_max_tokens,
            )
            return self._parse_sim_response(response.content or "{}")
        except Exception as e:
            # Fallback: return a generic success stub
            return {
                "status": "success",
                "tool_name": tool_call.tool_name,
                "note": f"Simulated response (generation failed: {e})",
            }

    def _build_tool_sim_prompt(self, tool_call: ToolCallRecord) -> str:
        """Construct the user prompt for the tool-response simulator."""
        parts = [
            "## Scenario Context",
            self._scenario_context,
            "",
            "## Tool Call",
            f"Tool: {tool_call.tool_name}",
            f"Arguments: {json.dumps(tool_call.arguments, ensure_ascii=False)}",
            "",
            "Generate a realistic JSON response for this tool call.",
        ]
        return "\n".join(parts)

    # ----- helpers -----

    def _build_scenario_context(self) -> str:
        """Extract a compact text summary of the scenario for the simulator."""
        parts = []

        # Task details (order info, product, dates, etc.)
        task = self.scenario.get("task", {})
        if task:
            parts.append(f"Task detail: {json.dumps(task, ensure_ascii=False)}")

        # Persona
        persona = self.scenario.get("persona", {})
        if persona:
            name = persona.get("Name", "Customer")
            parts.append(f"Customer name: {name}")

        # Opening message (contains order references)
        opening = self.scenario.get("first_customer_message", "")
        if opening:
            parts.append(f"Customer opening message: {opening}")

        # Scenario ID
        sid = self.scenario.get("scenario_id", "")
        if sid:
            parts.append(f"Scenario ID: {sid}")

        return "\n".join(parts) if parts else "(no scenario context available)"

    @staticmethod
    def _signature(tool_call: ToolCallRecord) -> str:
        args_norm = json.dumps(tool_call.arguments, sort_keys=True, ensure_ascii=False)
        return f"{tool_call.tool_name}::{args_norm}"

    @staticmethod
    def _parse_sim_response(text: str) -> Dict[str, Any]:
        """Parse JSON from the simulator LLM output."""
        t = text.strip()
        # Strip markdown fences
        if t.startswith("```"):
            lines = t.split("\n")
            t = "\n".join(lines[1:])
            if t.endswith("```"):
                t = t[:-3].strip()

        try:
            parsed = json.loads(t)
            if isinstance(parsed, dict):
                return parsed
            return {"data": parsed}
        except json.JSONDecodeError:
            # Try to extract an object
            start = t.find("{")
            end = t.rfind("}")
            if start != -1 and end != -1 and end > start:
                try:
                    return json.loads(t[start : end + 1])
                except json.JSONDecodeError:
                    pass
            return {"status": "success", "raw_response": t[:500]}
